# Generated by Django 3.0.5 on 2020-04-14 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_type', models.CharField(choices=[('7.5% на 45 дней', '7.5% на 45 дней')], default=0, max_length=900)),
                ('deposit_value', models.IntegerField(null=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Bank.Profile')),
            ],
            options={
                'verbose_name_plural': 'Deposits',
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_balance', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Bank.Profile')),
            ],
        ),
    ]
