# Generated by Django 3.0.5 on 2020-04-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0002_account_deposits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposits',
            name='deposit_type',
            field=models.CharField(choices=[('7.5% на 45 дней', '7.5% на 45 дней')], default=1, max_length=900),
        ),
    ]
