# Generated by Django 3.0.5 on 2020-04-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0003_auto_20200415_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposits',
            name='deposit_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
    ]
