# Generated by Django 3.0.5 on 2020-04-15 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0007_auto_20200415_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposits',
            name='deposit_value',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
