# Generated by Django 3.0.5 on 2020-04-16 15:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0009_auto_20200415_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposits',
            name='date',
            field=models.DateField(default=datetime.date.today, editable=False),
        ),
    ]
