# Generated by Django 3.0.5 on 2020-04-16 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0010_deposits_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposits',
            name='deposit_value',
        ),
        migrations.AddField(
            model_name='deposits',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='deposits',
            name='deposit_type',
            field=models.CharField(choices=[('под 7.51% на 45 дней', 'под 7.51% на 45 дней'), ('под 8.56% на 95 дней', 'под 8.56% на 95 дней'), ('под 8.64% на 185 дней', 'под 8.64% на 185 дней'), ('под 8.87% на 385 дней', 'под 8.87% на 385 дней'), ('под 9.25% на 735 дней', 'под 9.25% на 735 дней')], default=1, max_length=900),
        ),
    ]
