# Generated by Django 3.0.5 on 2020-04-17 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0011_auto_20200416_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposits',
            name='current_balance',
        ),
        migrations.AddField(
            model_name='deposits',
            name='deposit_income',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='deposits',
            name='deposit_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deposits',
            name='total_income',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='deposits',
            name='deposit_type',
            field=models.CharField(choices=[('под 11% на 45 дней', 'под 11% на 45 дней'), ('под 11.3% на 95 дней', 'под 11.3% на 95 дней'), ('под 12.8% на 185 дней', 'под 12.8% на 185 дней'), ('под 13.2% на 385 дней', 'под 13.2% на 385 дней'), ('под 12.5% на 735 дней', 'под 12.5% на 735 дней')], default=0, max_length=900),
        ),
    ]
