# Generated by Django 3.0.5 on 2020-04-17 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0012_auto_20200417_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposits',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=4),
        ),
    ]
