# Generated by Django 3.0.5 on 2020-04-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0014_auto_20200420_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposits',
            name='temporary_deposit_income',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='deposits',
            name='temporary_total_income',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, null=True),
        ),
    ]
