# Generated by Django 3.0.5 on 2020-04-21 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0016_auto_20200421_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=60, null=True, verbose_name='Имя'),
        ),
    ]
