# Generated by Django 3.0.5 on 2020-04-21 13:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0017_auto_20200421_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Текущий баланс счёта'),
        ),
        migrations.AlterField(
            model_name='citizenship',
            name='citizenship',
            field=models.CharField(max_length=60, verbose_name='Гражданство'),
        ),
        migrations.AlterField(
            model_name='city',
            name='city',
            field=models.CharField(max_length=60, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='deposits',
            name='deposit_type',
            field=models.CharField(choices=[('под 11% на 35 дней', 'под 11% на 35 дней'), ('под 12.5% на 95 дней', 'под 12.5% на 95 дней'), ('под 12% на 185 дней', 'под 12% на 185 дней'), ('под 12.1% на 275 дней', 'под 12.1% на 275 дней'), ('под 12.5% на 370 дней', 'под 12.5% на 370 дней'), ('под 12.5% на 735 дней', 'под 12.5% на 735 дней'), ('под 11% на 37 месяцев', 'под 11% на 37 месяцев')], default=0, max_length=900, verbose_name='Тип депозита'),
        ),
        migrations.AlterField(
            model_name='deposits',
            name='deposit_value',
            field=models.IntegerField(default=0, verbose_name='Сумма депозита'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ID_number',
            field=models.IntegerField(null=True, unique=True, verbose_name='Идентификационный номер'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address_projivaniya',
            field=models.CharField(max_length=100, null=True, verbose_name='Адрес проживания'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address_propiski',
            field=models.CharField(max_length=100, null=True, verbose_name='Адрес прописки'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_place',
            field=models.CharField(max_length=60, null=True, verbose_name='Место рождения'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='citizenship',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Bank.Citizenship', verbose_name='Гражданство'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city_projivaniya',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='city_projivaniya', to='Bank.City', verbose_name='Город проживания'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city_propiski',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='city_propiski', to='Bank.City', verbose_name='Город прописки'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='data_vidachi',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата выдачи'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='family',
            field=models.CharField(choices=[('Замужем/Женат', 'Замужем/Женат'), ('Не замужем/Не женат', 'Не замужем/Не женат')], default='неопределено', max_length=9999, verbose_name='Семейное положение'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='invalid',
            field=models.CharField(choices=[('Нет', 'Нет'), ('1-ая группа', '1-ая группа'), ('2-ая группа', '2-ая группа'), ('3-ая группа', '3-ая группа')], default=1, max_length=9999, verbose_name='Инвалидность'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='job',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='Место работы'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='kem_vidan',
            field=models.CharField(max_length=60, verbose_name='Кем выдан'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=60, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobile_phone',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='Моб. тел.'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='otchestvo',
            field=models.CharField(max_length=60, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='passport_number',
            field=models.IntegerField(null=True, unique=True, verbose_name='Номер паспорта'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='todd.png', upload_to='profile_pictures/', verbose_name='Личное фото'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='seria_pasporta',
            field=models.CharField(default='MP', max_length=2, verbose_name='Серия паспорта'),
        ),
    ]
