# Generated by Django 3.0.5 on 2020-04-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0018_auto_20200421_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pensioner',
            field=models.BooleanField(default=False, verbose_name='Пенсионер'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.BooleanField(choices=[(False, 'Женщина'), (True, 'Мужчина')], default=True, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='voenoobyazaniy',
            field=models.BooleanField(default=False, verbose_name='Военнообязаный'),
        ),
    ]
