# Generated by Django 3.0.5 on 2020-04-21 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0019_auto_20200421_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address_propiski',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='city_propiski',
        ),
    ]
