# Generated by Django 3.0.5 on 2020-04-21 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0020_auto_20200421_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposits',
            name='deposit_type',
            field=models.CharField(choices=[('под 11.3% на 95 дней', 'под 11.3% на 95 дней'), ('под 11.8% на 125 дней', 'под 11.8% на 125 дней'), ('под 12.8% на 185 дней', 'под 12.8% на 185 дней'), ('под 13% на 275 дней', 'под 13% на 275 дней'), ('под 13.2% на 385 дней', 'под 13.2% на 385 дней'), ('под 12.8% на 550 дней', 'под 12.8% на 550 дней'), ('под 12.5% на 735 дней', 'под 11% на 735 дней')], default=0, max_length=900, verbose_name='Тип депозита'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(max_length=20, null=True, verbose_name='Должность'),
        ),
    ]
