# Generated by Django 3.0.5 on 2020-04-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0021_auto_20200421_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposits',
            name='deposit_type',
            field=models.CharField(choices=[('под 11.2% на 3 месяца', 'под 11.2% на 3 месяца'), ('под 11.5% на 6 месяцев', 'под 11.5% на 6 месяцев'), ('под 12% на 9 месяцев', 'под 12% на 9 месяцев'), ('под 13% на 12 месяцев', 'под 13% на 12 месяцев'), ('под 13.5% на 15 месяцев', 'под 13.5% на 15 месяцев')], default=0, max_length=900, verbose_name='Тип депозита'),
        ),
    ]
